from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.by import By
driver = webdriver.Chrome()
driver.get("https://www.opencart.com/index.php?route=common/home")
driver.maximize_window()
driver.find_element_by_link_text('Login').click()
driver.find_element_by_id('input-email').send_keys('uname')
driver.find_element_by_id('input-password').send_keys('xxx')
driver.find_element_by_xpath('//div[@class="col-sm-6"]/child::button[1]').submit()
time.sleep(2)
driver.find_element_by_id('input-pin').send_keys('xxx')
driver.find_element_by_xpath('//*[@id="account-security"]/div[2]/div/div[1]/form/div[2]/button').click()
print('Login successful')
acc_page=driver.find_element_by_link_text("Edit your account details")
acc_page.click()
print("user entered into account page")
def edit_acc_details(user_name,first_name,last_name,company__,taxid__,email__,val__,variable):
    usr=driver.find_element_by_name("username")
    usr.clear()
    usr.send_keys(user_name)
    fname=driver.find_element_by_name("firstname")
    fname.clear()
    fname.send_keys(first_name)
    lname=driver.find_element_by_name("lastname")
    lname.clear()
    lname.send_keys(last_name)
    comp=driver.find_element_by_name("company")
    comp.clear()
    comp.send_keys(company__)
    taxid=driver.find_element_by_name("tax_id")
    taxid.clear()
    taxid.send_keys(taxid__)
    email=driver.find_element_by_name("email")
    email.clear()
    email.send_keys(email__)
    country=Select(driver.find_element(By.ID,'input-country'))
    country.select_by_value(val__)
    if(variable=='no'):
        noti1=driver.find_element_by_css_selector("input[value='0']")
        print(noti1.text)
        noti1.click()
    else:
        noti=driver.find_element_by_css_selector("input[value='1']")
        noti.click()
    driver.find_element_by_xpath("//*[@id='account-edit']/div/div/div[1]/form/div/button").click()
    print("account has been edited successfully")
    time.sleep(5)
edit_acc_details("XXXXX")
time.sleep(10)
dashboard=driver.find_element_by_link_text("Dashboard")
driver.quit()